version: 2
build:
  os: ubuntu-20.04  # <- add this line
  tools:
    python: "3.10"
    
sphinx:
  configuration: docs/conf.py

formats: all

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

